runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: autoaddress.app

libraries:
- name: webapp2
  version: latest
