runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /htmlfiles
  static_dir: htmlfiles
 
- url: /js
  static_dir: js

- url: /.*
  script: autocomplete.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
